# Site settings
name: Frederic Randall
title: Frederic Randall | Operations Manager
description: Operations manager with a passion for data anlysis and project managment.
url: https://AfredTX.github.io/
baseurl: ''
email: Fredrandall333@gmail.com
cover: https://AfredTX.github.io/img/og.png
logo: https://AfredTX.github.io/img/emojis/eagle.png
resume: https://acrobat.adobe.com/link/review?uri=urn:aaid:scds:US:d388cbbd-5b3c-3c97-b8d7-aff4bfef3301
social:
  - title: email
    url: mailto:FredRandall333@gmail.com
  - title: twitter
    url: https://twitter.com/FredericRandal4
  - title: github
    url: https://github.com/AfredTX
  - title: linkedin
    url: https://www.linkedin.com/in/frandall-iii/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
