# Site settings
name: Frederic Randall
title: Frederic Randall | Data & IT Operations Manager
description: Motivated change agent with a passion for data analysis and project management.
url: https://AfredTX.github.io/
baseurl: ''
email: Fredrandall333@gmail.com
cover: https://AfredTX.github.io/img/og.png
logo: https://AfredTX.github.io/img/emojis/eagle.png
resume: https://AfredTX.github.io/Frederic%20Randall%20Resume.pdf
social:
  - title: email
    url: mailto:FredRandall333@gmail.com
  - title: github
    url: https://github.com/AfredTX
  - title: linkedin
    url: https://www.linkedin.com/in/frandall-iii/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
